### ISSUE TITLE
Duplicate Channels

### ISSUE THREAD

**Issue by caterryan** [Test-And-Measure-Engineering/Dewesoft-Plugin-DeltaRMC#2]
Channels are duplicated when adding or removing from plugin setup. 

![unnamed](https://github.com/Test-And-Measure-Engineering/Dewesoft-Plugin-DeltaRMC/assets/101369240/76bf4f47-b96f-4e39-a52a-6cb006c0e045)

**Comment by Test-And-Measure-Engineering** [comment]
The actual problem is the device is not removed when deleting

Steps to reproduce:
Add a device
Delete same device
In measure screen, channels are still present

**Comment by Test-And-Measure-Engineering** [comment]
Fixed in release [v0.1.0-beta.3](https://github.com/Test-And-Measure-Engineering/Dewesoft-Plugin-DeltaRMC/releases/tag/v0.1.0-beta.3)
